export const projects = [
  {
    title: 'Intuitive Human Controlled Robotic Arm',
    description: "A custom-built robotic arm that utilizes a VR headset and controller to mimic a user’s arm movement.",
    image: '/images/robotArm2.png',
    tags: ['ROS', 'MoveIt', 'Python', 'Unity', 'CAD'],
    source: 'https://github.com/manff/capstone-robot',
    visit: '/robot-arm',
    id: 0,
  },
  {
    title: 'CHARLOTTE',
    description: "CHARLOTTE is developed to operate as a scientific exploration rover tasked with searching permanently shadowed craters on the Lunar south pole in search of water ice and geological signs of other volatiles.",
    image: '/images/charlotte.png',
    tags: ['CAD', 'Ansys', 'Flownex', 'ROS'],
    source: '',
    visit: '/charlotte',
    id: 1,
  },
  {
    title: 'VELOS',
    description: "ABS Tweaks or Arkaynine Boost Script is a collection of shell scripts written with the aim of enhancing the performance and battery life of an Android phone. It got 2 Lac+ downloads overall.",
    image: '/images/velos.png',
    tags: ['CAD', 'Ansys'],
    source: '',
    visit: '/velos',
    id: 2,
  },
  {
    title: 'AR App',
    description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
    image: '/images/snapit.jpg',
    tags: ['Unity', 'HoloLens', 'Smali'],
    source: '',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 4,
  },
  {
    title: 'ADD-ictive',
    description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
    image: '/images/addictiveAd.png',
    tags: ['Unity', 'C#'],
    source: '#',
    visit: '/addictive',
    id: 5,
  },
  {
    title: 'Clan Base',
    description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
    image: '/images/capps.jpg',
    tags: ['React', 'Rest API', 'Next.JS'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 6,
  },

];

export const TimeLineData = [
  { year: 2017, text: 'Started work at Chandler-Gilber Community College as a Math and Physics Tutor.', },
  { year: 2019, text: 'Started work at the ASU Luminosity Lab.', },
  { year: 2019, text: 'Started work at NXP Semiconductors as a Reliability Testing Intern.', },
  { year: 2020, text: 'Started work at Intel as a Student Process Engineer.', },
  { year: 2021, text: 'Graduated from ASU with a bachelors degree in Mechanical Engineering.', },
  { year: 2022, text: 'Will graduate from ASU with a masters degree in Robotics and Autonomous Systems.', },
];