export const projects = [
  {
    title: 'Clan Base',
    description: "Clan Base is a third-party companion website for Destiny 2 that utilizes the Bungie API to create a place for users to visualize data related to player interactions.",
    image: '/images/clanBase.png',
    tags: ['React', 'REST API', 'Next.JS', 'MongoDB'],
    source: 'https://github.com/ConnorNail/ClanBase',
    visit: '/clan-base',
    id: 0,
  },
  {
    title: 'ADD-ictive',
    description: "ADD-ictive is a mobile game developed using Unity for both iOS and Android. The game is like Suduko but requires players to use addition and subtraction to complete the puzzles.",
    image: '/images/addictiveAd.png',
    tags: ['Unity', 'C#', 'iOS', 'Android'],
    source: 'https://github.com/ConnorNail/Addition',
    visit: '/addictive',
    id: 1,
  },
  {
    title: 'Weekly',
    description: "Weekly seeks to provide users with a deep insight into their computer usage, provide feedback on productivity, and motivate establishing productive habits through online competitions.",
    image: '/images/weekly.png',
    tags: ['React', 'Electron', 'REST API', 'AWS'],
    source: '',
    visit: '/weekly',
    id: 1,
  },
  {
    title: 'Intuitive Human Controlled Robotic Arm',
    description: "A custom-built robotic arm that utilizes a VR headset and controller to mimic a user’s arm movement.",
    image: '/images/robotArm2.png',
    tags: ['ROS', 'MoveIt', 'Python', 'Unity', 'CAD'],
    source: 'https://github.com/ConnorNail/capstone-robot', 
    visit: '/robot-arm',
    id: 2,
  },
  {
    title: 'CHARLOTTE',
    description: "CHARLOTTE is developed to operate as a scientific exploration rover tasked with searching permanently shadowed craters on the Lunar south pole in search of water ice.",
    image: '/images/charlotte.png',
    tags: ['CAD', 'Ansys', 'Flownex', 'ROS'],
    source: '',
    visit: '/charlotte',
    id: 3,
  },
  {
    title: 'VELOS',
    description: "VELOS is a configurable multi-probe system that is launched from a lander into a permanently shadowed region of the lunar south pole.",
    image: '/images/velos.png',
    tags: ['CAD', 'Ansys'],
    source: '',
    visit: '/velos',
    id: 4,
  },
  {
    title: 'Chess Robot',
    description: "A pick and place robotic arm designed for playing chess. A computed torque control system was designed for this system and simulated using Simulink and MATLAB.",
    image: '/images/chessRobot1.png',
    tags: ['MATLAB', 'Simulink', 'Solidworks'],
    source: '',
    visit: '/chess-robot',
    id: 5,
  },
  

];

export const TimeLineData = [
  { year: 2019, text: 'Started work at ASU in the Luminosity Lab.', },
  { year: 2019, text: 'Started work at NXP Semiconductors as a Reliability Testing Intern.', },
  { year: 2020, text: 'Started work at Intel as a Student Process Engineer.', },
  { year: 2021, text: 'Graduated from ASU with a bachelors degree in Mechanical Engineering.', },
  { year: 2022, text: 'Started working to help Weekly, LLC develop their website.', },
  { year: 2022, text: 'Graduated from ASU with a masters degree in Robotics and Autonomous Systems.', },
  { year: 2023, text: 'Working with you to advance your corporate mission.', },
];